apiVersion: v1 # Descriptor conforms to version v1 of Kubernetes API
kind: Pod # Select Pod resource
metadata:
  name: kube-starter # The name of the pod
spec:
  containers:
    - name: kube-container # The name of the container
      image: localhost:5000/kube-image # Image to create the container
      imagePullPolicy: IfNotPresent # The image is pulled only if it is not already present locally.
      ports:
        - containerPort: 3002 # The port the app is listening on
          protocol: TCP