apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller
spec:
  replicas: 2 # number of the pod
  selector: # The pod selector determining what pods the replication controller is operating on
    app: kube-starter # label value
  template: # pod template
    metadata:
      labels:
        app: kube-starter # label value
    spec:
      containers:
        - image: localhost:5000/kube-image # image used to run container
          name: kube-container # name of the container
          imagePullPolicy: IfNotPresent # The image is pulled only if it is not already present locally.
          ports:
            - containerPort: 3002 # pod of the container
