apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-starter
  template:
    metadata:
      labels:
        app: kube-starter
    spec:
      containers:
        - image: localhost:5000/kube-image
          name: kube-container
          imagePullPolicy: IfNotPresent # The image is pulled only if it is not already present locally.
          ports:
            - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-test
spec:
  selector:
    app: kube-starter
  type: NodePort
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 31000 # Range from 30000 - 32767
